"""Authorized workflow operations and source evidence."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from flow1c import context as runtime
from flow1c import publication as publication
from flow1c import readiness as readiness
from flow1c import registry as registry_service
from flow1c import setup as setup_service
from flow1c import storage as storage
from flow1c import system as system
from flow1c import work_items as work_items
from flow1c.errors import WorkflowError
from flow1c.results import OperationResult
from flow1c.workflow import state as gate_state
from scripts import flow1c_policy as policy
from scripts import flow1c_sections_policy as sections_policy


def write_free_draft(
    gate: dict[str, Any], args: argparse.Namespace, content: str, *, product_root: Path
) -> OperationResult:
    if gate["mode"] != "draft" or args.target != "draft":
        raise WorkflowError("Free work can write only target=draft in draft mode")
    if not content.strip():
        raise WorkflowError("Draft content is empty")
    root = gate_state.request_root(gate, product_root=product_root)
    target = gate_state.safe_request_file(root, str(args.path or ""), markdown=True)
    if "UNVERIFIED_DRAFT" not in content:
        content = (
            "> **UNVERIFIED_DRAFT** — рабочий черновик; открытые вопросы и допущения требуют уточнения.\n\n"
            + content
        )
    storage.write_text(target, "<!-- Generated by Flow1C. -->\n\n" + content)
    evidence_path, evidence = gate_state.evidence_for_gate(gate, product_root=product_root)
    relative = str(target.relative_to(root)).replace("\\", "/")
    evidence.setdefault("changed_files", []).append(
        {"target": "draft", "path": relative, "sha256": storage.sha256(target)}
    )
    storage.write_json(evidence_path, evidence)
    _value = {"state": "WRITTEN", "absolute_path": str(target)}
    return OperationResult(_value, 0)


def agent_inspect(args: argparse.Namespace, *, product_root: Path) -> OperationResult:
    gate = gate_state.load_gate(
        args.gate_id,
        states={"READY", "READY_WITH_DEVIATIONS", "UNVERIFIED_DRAFT", "WAITING_USER"},
        product_root=product_root,
    )
    gate_state.require_gate_tool(gate, "flow1c_inspect", product_root=product_root)
    root = (
        product_root.resolve()
        if args.scope == "workflow"
        else gate_state.request_root(gate, product_root=product_root)
    )
    limit = max(1, min(int(args.max_chars), 40000))
    excluded = {".git", ".venv", ".workspace", "node_modules", "__pycache__"}
    extensions = {".md", ".py", ".ps1", ".json", ".js", ".ts", ".txt", ".yaml", ".csv"}

    def allowed(p: Path) -> bool:
        relative = p.relative_to(root)
        return (
            p.suffix.lower() in extensions
            and (not any((part in excluded for part in relative.parts)))
            and (not p.name.startswith((".flow1c.local", ".env")))
            and storage.path_is_within(p, root)
            and (not storage.is_reparse_or_symlink(p))
        )

    if args.path:
        target = gate_state.safe_request_file(root, args.path)
        if not target.is_file() or not allowed(target):
            raise WorkflowError(
                "Only workflow text and accepted request text can be read; configuration sources require RLM"
            )
        candidates = [target]
    else:
        candidates = []
        for directory, dirs, names in os.walk(root, followlinks=False):
            dirs[:] = sorted(
                (
                    d
                    for d in dirs
                    if d not in excluded
                    and (not storage.is_reparse_or_symlink(Path(directory) / d))
                )
            )
            for name in sorted(names):
                p = Path(directory) / name
                if allowed(p):
                    candidates.append(p)
            if len(candidates) >= 1000:
                break
    result = []
    remaining = limit
    for p in candidates[:1000]:
        if not args.path and (not args.query):
            text = str(p.relative_to(root))
        else:
            if p.stat().st_size > 2 * 1024 * 1024:
                continue
            lines = p.read_text(encoding="utf-8-sig", errors="replace").splitlines()
            start = max(1, int(args.start_line))
            text = "\n".join(
                (
                    f"{i}: {line}"
                    for i, line in enumerate(lines, 1)
                    if i >= start and (not args.query or args.query.casefold() in line.casefold())
                )
            )
        if not text:
            continue
        result.append(
            {"path": str(p.relative_to(root)).replace("\\", "/"), "content": text[:remaining]}
        )
        remaining -= len(text)
        if remaining <= 0:
            break
    _value = {
        "state": "READ",
        "items": result,
        "truncated": remaining <= 0 or len(candidates) >= 1000,
    }
    return OperationResult(_value, 0)


def draft_promote(args: argparse.Namespace, *, product_root: Path) -> OperationResult:
    gate = gate_state.load_gate(args.gate_id, states={"DRAFT_COMPLETE"}, product_root=product_root)
    gate_state.require_gate_tool(gate, "flow1c_promote", product_root=product_root)
    if not args.confirmed:
        raise WorkflowError("Explicit user agreement to attach this draft is required")
    reference = runtime.resolve_reference_args(args, product_root=product_root)
    code = reference["work_reference"]
    if not code:
        raise WorkflowError("A user-assigned project or task reference is required")
    _, manifest = work_items.load_manifest(code, product_root=product_root)
    requirements = list(args.requirements or gate.get("requirements", []))
    if not requirements:
        raise WorkflowError("Specify the requirement IDs this draft addresses")
    mismatch = work_items.reference_mismatch(code, requirements, product_root=product_root)
    if mismatch:
        raise WorkflowError(mismatch)
    links = storage.read_json(
        runtime.project_data_root(product_root=product_root) / "registry/normalized/links.json", {}
    ).get("requirement_to_specification", {})
    known = storage.read_json(
        runtime.project_data_root(product_root=product_root) / "registry/normalized/requirements.json",
        {},
    )
    if any((req not in known or (links.get(req) and links[req] != code) for req in requirements)):
        raise WorkflowError(
            "Requirement registry is missing or assigns a requirement to another work item"
        )
    source = gate_state.request_root(gate, product_root=product_root).resolve()
    target_root = (
        work_items.work_item_root(code, product_root=product_root) / "input" / "drafts"
    ).resolve()
    target = target_root / gate["request_id"]
    if not storage.path_is_within(target, target_root):
        raise WorkflowError("Invalid promotion destination")
    if target.exists():
        raise WorkflowError("Draft has already been attached; existing materials are preserved")
    if any((storage.is_reparse_or_symlink(p) for p in source.rglob("*"))):
        raise WorkflowError("Draft contains a symlink or reparse point")
    shutil.copytree(source, target)
    storage.write_json(
        target / "provenance.json",
        {
            "generated_by": "Flow1C",
            "request_id": gate["request_id"],
            "source": str(source),
            "code": code,
            "requirements": requirements,
            "document_status": "UNVERIFIED_DRAFT",
            "attached_at": storage.utc_now(),
        },
    )
    _value = {
        "state": "ATTACHED",
        "destination": str(target),
        "document_status": "UNVERIFIED_DRAFT",
        "work_item_status": manifest["status"],
    }
    return OperationResult(_value, 0)


def agent_diff(args: argparse.Namespace, *, product_root: Path) -> OperationResult:
    gate = gate_state.load_gate(
        args.gate_id,
        states={"READY", "READY_WITH_DEVIATIONS", "UNVERIFIED_DRAFT"},
        product_root=product_root,
    )
    gate_state.require_gate_tool(gate, "flow1c_diff", product_root=product_root)
    code = str(gate.get("work_reference") or gate.get("task_reference") or gate.get("code") or "")
    if not code:
        raise WorkflowError("A user-assigned task reference is required for an extension diff.")
    _, manifest = work_items.load_manifest(code, product_root=product_root)
    diff_state, error = system.extension_git_state(code, manifest, product_root=product_root)
    if error or diff_state is None:
        raise WorkflowError(error or "Extension diff is unavailable.")
    extension = Path(diff_state["path"])
    result = subprocess.run(
        ["git", "diff", "--no-ext-diff", "--unified=80", f"{diff_state['base']}...HEAD"],
        cwd=extension,
        text=True,
        encoding="utf-8",
        errors="replace",
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        raise WorkflowError(result.stderr.strip() or "Cannot build extension diff.")
    if len(result.stdout) > int(args.max_chars):
        raise WorkflowError(
            f"Bounded diff exceeds {args.max_chars} characters; narrow it before analysis."
        )
    digest = hashlib.sha256(result.stdout.encode("utf-8")).hexdigest()
    evidence_id = f"DIFF-{digest[:12]}"
    evidence_path, evidence = gate_state.evidence_for_gate(gate, product_root=product_root)
    evidence["diff"] = {**diff_state, "sha256": digest, "evidence_id": evidence_id}
    storage.write_json(evidence_path, evidence)
    _value = {
        "state": "READY",
        "evidence_id": evidence_id,
        "diff": diff_state,
        "sha256": digest,
        "content": result.stdout,
    }
    return OperationResult(_value, 0)


def agent_write(args: argparse.Namespace, *, product_root: Path) -> OperationResult:
    gate = gate_state.load_gate(
        args.gate_id,
        states={"READY", "READY_WITH_DEVIATIONS", "UNVERIFIED_DRAFT"},
        product_root=product_root,
    )
    stage = gate_state.require_gate_tool(gate, "flow1c_write", product_root=product_root)
    code = str(gate.get("code") or "")
    content = sys.stdin.read() if args.content_stdin else str(args.content or "")
    if gate.get("mode", "formal") != "formal":
        return write_free_draft(gate, args, content, product_root=product_root)
    if args.target == "extension":
        if "extension" not in stage.get("writable_targets", []):
            raise WorkflowError("This operation may not modify the extension checkout.")
        _, local = runtime.load_config(product_root=product_root)
        root = Path(str(local.get("extension_path", ""))).resolve()
        _, manifest = work_items.load_manifest(code, product_root=product_root)
        errors = policy.stage_errors(stage, manifest)
        item_root = work_items.work_item_root(code, product_root=product_root)
        errors.extend(
            (
                f"required input is missing: {relative}"
                for relative in stage.get("required_files", [])
                if not gate_state.meaningful_file(item_root / relative)
            )
        )
        if errors:
            raise WorkflowError("Extension write prerequisites changed: " + "; ".join(errors))
        diff_state, error = system.extension_git_state(code, manifest, product_root=product_root)
        if error or diff_state is None or diff_state["branch"] != diff_state["expected_branch"]:
            raise WorkflowError(error or "Extension branch does not match the work-item manifest.")
    else:
        if not code or not any(
            (value.startswith("work-item") for value in stage.get("writable_targets", []))
        ):
            raise WorkflowError("This operation may not modify work-item documentation.")
        root = work_items.work_item_root(code, product_root=product_root)
    target = (root / args.path).resolve()
    if not storage.path_is_within(target, root):
        raise WorkflowError("Write target is outside the permitted root.")
    if args.target == "work-item":
        relative_target = str(target.relative_to(root)).replace("\\", "/")
        allowed_prefixes = {
            "functional-spec": ("analysis/", "specification/functional-spec.md"),
            "functional-review": ("reviews/functional-review.md",),
            "technical-design": (
                "specification/technical-design.md",
                "reviews/technical-review.md",
            ),
            "technical-implementation": ("specification/technical-implementation.md",),
            "code-review": ("implementation/code-review.md",),
            "testing": ("testing/",),
        }.get(str(gate.get("operation")), ())
        if not any(
            (
                relative_target == value.rstrip("/") or relative_target.startswith(value)
                for value in allowed_prefixes
            )
        ):
            raise WorkflowError(
                f"Documentation path {relative_target} is not allowed for {gate.get('operation')}."
            )
    if (
        gate["state"] in {"UNVERIFIED_DRAFT", "READY_WITH_DEVIATIONS"}
        and args.target != "work-item"
    ):
        raise WorkflowError("An unverified draft may not modify extension sources.")
    if (
        gate["state"] in {"UNVERIFIED_DRAFT", "READY_WITH_DEVIATIONS"}
        and "UNVERIFIED_DRAFT" not in content
    ):
        content = (
            "> **UNVERIFIED_DRAFT:** обязательные источники отсутствуют; документ нельзя согласовывать или публиковать.\n\n"
            + content
        )
    if args.target == "work-item" and str(gate.get("operation")) == "technical-implementation":
        sections_policy.validate_section_content("technical-implementation", content)
    storage.write_text(target, content)
    evidence_path, evidence = gate_state.evidence_for_gate(gate, product_root=product_root)
    relative = str(target.relative_to(root)).replace("\\", "/")
    record = {"target": args.target, "path": relative, "sha256": storage.sha256(target)}
    evidence.setdefault("changed_files", []).append(record)
    storage.write_json(evidence_path, evidence)
    _value = {"state": "WRITTEN", **record, "absolute_path": str(target)}
    return OperationResult(_value, 0)


def agent_action(args: argparse.Namespace, *, product_root: Path) -> OperationResult:
    gate = gate_state.load_gate(
        args.gate_id,
        states={
            "READY",
            "READY_WITH_DEVIATIONS",
            "NEEDS_INPUT",
            "NEEDS_CONFIRMATION",
            "WAITING_BACKGROUND",
            "BLOCKED",
            "NON_COMPLIANT",
        },
        product_root=product_root,
    )
    if gate_state.recoverable_update_action_gate(gate):
        if args.action != "update":
            raise WorkflowError("Only an update retry is allowed for this recoverable gate.")
    else:
        if gate["state"] == "NON_COMPLIANT":
            raise WorkflowError("Agent gate state NON_COMPLIANT is not allowed for this action.")
        gate_state.require_gate_tool(gate, "flow1c_action", product_root=product_root)
    operation = str(gate.get("operation"))
    action = str(args.action)
    try:
        parameters = json.loads(args.parameters_json or "{}")
    except json.JSONDecodeError as exc:
        raise WorkflowError(f"Invalid action parameters JSON: {exc}") from exc
    if not isinstance(parameters, dict):
        raise WorkflowError("Action parameters must be a JSON object.")
    if action == "update" and gate.get("update_id") and (not parameters.get("new_run")):
        for flag, alias in (
            ("allow_external_updates", "allowExternalUpdates"),
            ("skip_external_tool_updates", "skipExternalToolUpdates"),
            ("repair_prerequisites", "repairPrerequisites"),
        ):
            if flag not in parameters and alias in parameters:
                parameters[flag] = parameters[alias]
            if flag not in parameters and (gate.get("update_result") or {}).get("options", {}).get(
                flag
            ):
                parameters[flag] = True
    allowed = {
        "setup": {
            "setup-audit",
            "setup-plan",
            "setup-bootstrap",
            "setup-configure",
            "setup-status",
            "setup-resume",
            "doctor",
        },
        "update": {"update", "update-diagnose", "doctor"},
        "registry": {"registry-import"},
        "functional-spec": {"fs-start", "provisional-start", "registry-reconcile"},
        "functional-review": {"provisional-start", "registry-reconcile"},
        "technical-design": {"provisional-start", "registry-reconcile"},
        "technical-implementation": {"provisional-start", "registry-reconcile"},
        "code-review": {"provisional-start", "registry-reconcile"},
        "testing": {"provisional-start", "registry-reconcile"},
        "status": {"status"},
        "publish": {"publish"},
    }
    if action not in allowed.get(operation, set()):
        raise WorkflowError(f"Action {action} is not allowed for operation {operation}.")
    if action == "provisional-start":
        bypasses = [
            item for item in gate.get("deviations", []) if item.get("type") == "registry_bypass"
        ]
        if not bypasses:
            raise WorkflowError("provisional-start requires an explicit registry_bypass deviation")
        try:
            reference = policy.resolve_work_reference(
                parameters.get("task_reference")
                or gate.get("task_reference")
                or gate.get("work_reference"),
                parameters.get("project_reference") or gate.get("project_reference"),
            )
        except ValueError as exc:
            raise WorkflowError(str(exc)) from exc
        brief = str(parameters.get("user_brief") or gate.get("summary") or "")
        requirements = parameters.get("requirements") or []
        if not isinstance(requirements, list):
            raise WorkflowError("requirements must be a list of user-supplied identifiers")
        target = work_items.create_provisional_work_item(
            reference,
            title=str(
                parameters.get("title")
                or gate.get("summary")
                or reference.get("work_reference")
                or ""
            ),
            user_brief=brief,
            deviation=bypasses[-1],
            requirements=[str(item) for item in requirements],
            product_root=product_root,
        )
        code = str(reference["work_reference"])
        manifest = storage.read_json(target / "manifest.yaml", {})
        basis = manifest["requirement_basis"]
        gate.update(
            **reference,
            code=code,
            work_item_exists=True,
            traceability_mode="provisional",
            state="SUPERSEDED",
            compliance="DEVIATED",
        )
        evidence_path = target / "evidence" / f"{operation}-{gate['gate_id']}.json"
        evidence = {
            "schema_version": 1,
            "gate_id": gate["gate_id"],
            "operation": operation,
            "code": code,
            **reference,
            "traceability_mode": "provisional",
            "requirement_basis": {"type": "user_brief", "sha256": basis["sha256"]},
            "registry_snapshot_sha256": None,
            "deviations": gate["deviations"],
            "revalidation_required": True,
            "context_sha256": "",
            "artifacts": [],
            "diff": None,
            "rlm_queries": [],
            "source_reads": [],
            "bsl_ls": None,
            "changed_files": [],
            "created_at": storage.utc_now(),
        }
        storage.write_json(evidence_path, evidence)
        gate["evidence_path"] = str(evidence_path)
        gate_state.refresh_gate_actions(gate, product_root=product_root)
        gate_state.save_gate(gate, product_root=product_root)
        _value = {
            "state": "ACTION_COMPLETE",
            "next": "flow1c_begin",
            "work_item": str(target),
            "traceability_mode": "provisional",
        }
        return OperationResult(_value, 0)
    if action == "registry-reconcile":
        source = str(parameters.get("source") or "").strip()
        code = str(
            parameters.get("task_reference")
            or parameters.get("code")
            or gate.get("work_reference")
            or gate.get("code")
            or ""
        )
        if not source or not code:
            raise WorkflowError(
                "registry-reconcile requires source and a user-supplied work reference"
            )
        mappings = parameters.get("mappings") or {}
        if not isinstance(mappings, dict):
            raise WorkflowError("mappings must be an object")
        exit_code, result = work_items.reconcile_registry(
            code, source, {str(k): str(v) for k, v in mappings.items()}, product_root=product_root
        )
        if exit_code == 0:
            gate.update(action_completed=action, state="NEEDS_INPUT", traceability_mode="registry")
            gate_state.refresh_gate_actions(gate, product_root=product_root)
            gate_state.save_gate(gate, product_root=product_root)
        _value = result
        return OperationResult(_value, exit_code)
    if action == "update-diagnose":
        if parameters:
            raise WorkflowError("Update diagnostics accept no paths, commands or configuration changes.")
        from flow1c.update_diagnostics import diagnose_update

        return OperationResult(diagnose_update(gate, product_root=product_root), 0)
    if action in {
        "setup-status",
        "setup-resume",
        "setup-audit",
        "setup-plan",
        "setup-bootstrap",
        "setup-configure",
        "update",
    }:
        return setup_service.execute_action(action, parameters, gate, product_root=product_root)
    if action == "status":
        gate["action_completed"] = "status"
        gate_state.save_gate(gate, product_root=product_root)
        _value = {
            "state": "ACTION_COMPLETE",
            "next": "flow1c_complete",
            "content": publication.render_status(product_root=product_root),
        }
        return OperationResult(_value, 0)
    if action == "doctor":
        return readiness.doctor(
            argparse.Namespace(
                json=True, profile=parameters.get("profile"), operation=parameters.get("operation")
            ),
            product_root=product_root,
        )
    if action == "registry-import":
        source = str(parameters.get("source", "")).strip()
        if not source:
            raise WorkflowError("registry-import requires source")
        imported = registry_service.registry_import(
            argparse.Namespace(
                file=source, allow_errors=bool(parameters.get("allow_errors", False))
            ),
            product_root=product_root,
        )
        exit_code, registry_result = (imported.exit_code, imported.value)
        if exit_code in {0, 1} and registry_result.get("state") in {"READY", "PARTIAL"}:
            gate["state"] = "READY"
            gate["action_completed"] = action
            gate["registry_import"] = registry_result
            gate_state.refresh_gate_actions(gate, product_root=product_root)
            gate_state.save_gate(gate, product_root=product_root)
        else:
            gate["state"] = "NEEDS_CONFIRMATION"
            gate["registry_import"] = registry_result
            gate_state.refresh_gate_actions(gate, product_root=product_root)
            gate_state.save_gate(gate, product_root=product_root)
        accepted = exit_code in {0, 1} and registry_result.get("state") in {"READY", "PARTIAL"}
        _value = {
            **registry_result,
            "state": "ACTION_COMPLETE" if accepted else "NEEDS_CONFIRMATION",
            "next": "flow1c_complete" if accepted else "registry-bypass-or-fix",
        }
        return OperationResult(_value, exit_code)
    if action == "fs-start":
        code = str(
            parameters.get("task_reference")
            or parameters.get("code")
            or gate.get("work_reference")
            or gate.get("code")
            or ""
        )
        started = work_items.fs_start(
            argparse.Namespace(
                code=code,
                task_reference=parameters.get("task_reference"),
                project_reference=parameters.get("project_reference"),
                g_number=None,
                reference_kind=parameters.get("reference_kind", gate.get("reference_kind", "auto")),
                title=parameters.get("title"),
                requirements=parameters.get("requirements"),
                create_branch=bool(parameters.get("create_branch", False)),
            ),
            product_root=product_root,
        )
        exit_code = started.exit_code
        created = started.value
        output = work_items.describe_created_work_item(created)
        _value = {
            "state": "ACTION_COMPLETE" if exit_code == 0 else "BLOCKED",
            "next": "flow1c_begin" if exit_code == 0 else None,
            "output": output,
        }
        return OperationResult(_value, exit_code)
    if action == "publish":
        if not parameters.get("confirmed"):
            return OperationResult(
                {
                    "state": "NEEDS_CONFIRMATION",
                    "user_message": "Для этого изменения требуется явное подтверждение пользователя.",
                },
                1,
            )
        if gate["state"] != "READY":
            raise WorkflowError(
                "Publication requires a READY gate; confirmation does not override missing checks"
            )
        work_reference = str(
            gate.get("work_reference")
            or gate.get("code")
            or parameters.get("task_reference")
            or parameters.get("code")
            or ""
        )
        publication.validate_publication(
            work_reference, str(parameters.get("phase", "technical")), product_root=product_root
        )
        published = publication.pr_create(
            argparse.Namespace(
                code=work_reference,
                phase=str(parameters.get("phase", "technical")),
                title=parameters.get("title"),
            ),
            product_root=product_root,
        )
        exit_code = published.exit_code
        response = published.value
        output = (
            response.get("html_url")
            or response.get("url")
            or json.dumps(response, ensure_ascii=False)
        )
        if exit_code == 0:
            gate["state"] = "READY"
            gate["action_completed"] = action
            gate_state.save_gate(gate, product_root=product_root)
        _value = {
            "state": "ACTION_COMPLETE" if exit_code == 0 else "BLOCKED",
            "next": "flow1c_complete" if exit_code == 0 else None,
            "output": output,
        }
        return OperationResult(_value, exit_code)
    raise WorkflowError(f"Unsupported action: {action}")
